# Generated by Django 3.2.9 on 2022-04-09 04:13

from django.contrib.postgres.search import SearchVector

from django.db import migrations


def update_search_vector(apps, schema_editor):
    Cities = apps.get_model('cities', 'Cities')
    Cities.objects.all().update(search_vector=(
        SearchVector('citie', weight='A') +
        SearchVector('admin_name', weight='B')
    ))

class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_search_vector'),
    ]

    operations = [
        migrations.RunPython(update_search_vector, elidable=True),
    ]
