# Generated by Django 3.2.9 on 2022-04-09 20:45

from django.contrib.postgres.operations import TrigramExtension
from django.db import connection, migrations


def update_cities_search_word(apps, schema_editor):
    sql = """
        INSERT INTO cities_citiessearchword (word)
        SELECT word FROM ts_stat('
          SELECT to_tsvector(''simple'', citie) ||
                 to_tsvector(''simple'', coalesce(admin_name, ''''))
            FROM cities_cities
        ');
    """
    with connection.cursor() as cursor:
        cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_citiessearchword'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(sql="""
            CREATE INDEX IF NOT EXISTS cities_search_word_trigram_index
                ON cities_citiessearchword
             USING gin (word gin_trgm_ops);
        """, elidable=True),
        migrations.RunPython(update_cities_search_word, elidable=True),
    ]
