# docker-compose.yml

version: "3.8"

services:

  database:
    container_name: db
    environment:
      - POSTGRES_DB=cities
      - POSTGRES_USER=jairo
      - POSTGRES_PASSWORD=jairo
    image: postgres:14.1
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.14.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  django: &django
    build:
      context: ./server
    
    image: local_django
    depends_on:
      - database
      - elasticsearch
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=cities
      - SQL_USER=jairo
      - SQL_PASSWORD=jairo
      - SQL_HOST=db
      - SQL_PORT=5432
      - ES_HOSTS=http://elasticsearch:9200
    command: [ "bash", "start.sh" ]
    ports:
      - 8000
    volumes:
      - ./server:/usr/src/app
      - static:/usr/src/app/static
  

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: local_celeryworker
    depends_on:
      - redis
      - database 
    ports: []
    command: [ "bash", "worker.sh" ]
    #/start-celeryworker

  celerybeat:
    <<: *django
    image: local_celerybeat
    depends_on:
      - redis
      - database
    ports: []
    command: [ "bash", "beat.sh" ]
    #/start-celerybeat
  
  flower:
    <<: *django
    image: local_flower
    ports:
      - "5555:5555"
    command: [ "bash", "flower.sh" ]
  
  client:
    build:
      context: ./client
    command: [ "npm", "start" ]
    container_name: client
    depends_on:
      - django
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    depends_on:
      - django
      - client
    ports:
      - 8003:80
    restart: always
    volumes:
      - static:/usr/src/app/static
  
volumes:
  database:
  elasticsearch:
  static: