# docker-compose.yml

version: "3.8"

services:

  database:
    container_name: db
    environment:
      - POSTGRES_DB=cities
      - POSTGRES_USER=jairo
      - POSTGRES_PASSWORD=jairo
    image: postgres:14.1
    ports:
      - "5433:5432"
    volumes:
      - database:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.14.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  server:
    build:
      context: ./server
    container_name: server
    depends_on:
      - database
      - elasticsearch
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=cities
      - SQL_USER=jairo
      - SQL_PASSWORD=jairo
      - SQL_HOST=db
      - SQL_PORT=5432
      - ES_HOSTS=http://elasticsearch:9200
    command: [ "bash", "start.sh" ]
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app

  client:
    build:
      context: ./client
    command: [ "npm", "start" ]
    container_name: client
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app

volumes:
  database:
  elasticsearch: